name: Deploy to DigitalOcean

on: workflow_dispatch

#on:
  #push:
   #branches:
    # - stages  # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy Files to Droplet
        run: |
          scp -r ./ root@128.199.16.184:var/www/html/lms
